#!/bin/sh
# Emits buildenv_libs.h: every i386 soname the build environment ships, with the real file it resolves to (the filename carries the version)
# and the symbol versions it defines.
set -e
grep -q '^VERSION_CODENAME=sniper' /etc/os-release || { echo "Not running inside the sniper SDK" >&2; }

entries=$(for f in /lib/i386-linux-gnu/*.so* /usr/lib/i386-linux-gnu/*.so*; do
	[ -f "$f" ] && [ ! -L "$f" ] || continue
	so=$(readelf -d "$f" 2>/dev/null | sed -n 's/.*(SONAME).*\[\(.*\)\]$/\1/p')
	[ -n "$so" ] || continue
	vers=$(readelf -V "$f" 2>/dev/null | sed -n '/Flags: BASE/d; s/.*Index: .*Name: //p' | tr '\n' ' ')
	# libcurl puts every symbol under one version, so only the symbol list tells releases apart.
	syms=
	case $so in libcurl*) syms=$(nm -D --defined-only "$f" | sed -n 's/@.*//; s/^[0-9a-f]* [^A] //p' | tr '\n' ' ') ;; esac
	printf '\t{"%s", "%s", "%s", "%s"},\n' "$so" "${f##*/}" "$vers" "$syms"
done | sort -u)
[ -n "$entries" ] || { echo "no i386 libraries found" >&2; exit 1; }

echo "// Generated by gen_buildenv_libs.sh, do not edit."
echo "static const char kBuildEnvBuild[] = \"$(sed -n 's/^BUILD_ID=//p' /etc/os-release | tr -d '"')\";"
echo "// {soname, file, version definitions, exported symbols (libcurl only)}"
echo "static const char *const kBuildEnvLibs[][4] = {"
echo "$entries"
echo "};"
