#!/bin/sh
# Emits buildenv_libs.h: every i386 soname the build environment ships, with the real file it resolves to (the filename carries the version).
set -e
grep -q '^VERSION_CODENAME=sniper' /etc/os-release || { echo "Not running inside the sniper SDK" >&2; }

entries=$(for f in /lib/i386-linux-gnu/*.so* /usr/lib/i386-linux-gnu/*.so*; do
	[ -f "$f" ] && [ ! -L "$f" ] || continue
	so=$(readelf -d "$f" 2>/dev/null | sed -n 's/.*(SONAME).*\[\(.*\)\]$/\1/p')
	[ -n "$so" ] && printf '\t{"%s", "%s"},\n' "$so" "${f##*/}"
done | sort -u)
[ -n "$entries" ] || { echo "no i386 libraries found" >&2; exit 1; }

echo "// Generated by gen_buildenv_libs.sh, do not edit."
echo "static const char kBuildEnvBuild[] = \"$(sed -n 's/^BUILD_ID=//p' /etc/os-release | tr -d '"')\";"
echo "static const char *const kBuildEnvLibs[][2] = {"
echo "$entries"
echo "};"
